version: '3'
services:
#  nginx-proxy:
#    image: jwilder/nginx-proxy
#    ports:
#    - "80:80"
#    volumes:
#    - /var/run/docker.sock:/tmp/docker.sock:ro
    
  mongodb:
    build: mongodb
    ports:
    - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pwd
      MONGO_INITDB_DATABASE: testdb

  backend:
    # restart: always
    build: backend
    ports:
    - 3000:3000
    user: "node"
    depends_on:
    - mongodb
    environment:
    - SECRET=lol
    - SERVER_ACCESS_TOKEN=ghjmnbv44cdftgy
    - PRIMUS_URL=http://primus:2333
    env_file: dev.env

  frontend:
    build: frontend
    ports:
    - 8001:80
    environment:
    - PORT=4200
    - PRIMUS_URL=http://localhost:2333
    - API_URL=http://localhost:3001
    env_file: dev.env
#    command: "./node_modules/.bin/ng build --prod"

  primus:
    restart: always
    build: primus
    ports:
    - 2333:2333
    depends_on:
    - mongodb
    environment:
    - PORT=2333
    - SERVER_ACCESS_TOKENS="ghjmnbv44cdftgy rtyuh9784b"
    env_file: dev.env
