version: '3'
services:
  mongodb:
    container_name: ${SUBDOMAIN:-app}.mongodb
    build: mongodb
    restart: "always"
    ports:
      - "27017:27017"
    env_file: env/mongodb.env
    labels:
      - "traefik.backend=mongodb"
      - "traefik.port=27017"
      - "traefik.enable=false"

  backend:
    container_name: ${SUBDOMAIN:-app}.backend
    depends_on:
      - mongodb
    build: backend
    restart: "always"
    networks:
      - web
      - default
    env_file: env/backend.env
    command: npm start
    ports:
      - "3005:3005"
    labels:
      - "traefik.docker.network=web"
      - "traefik.backend=loopback"
      - "traefik.frontend.rule=Host:api.${SUBDOMAIN:-app}.${DOMAIN:-localhost}"
      - "traefik.port=3005"
      - "traefik.protocol=http"
      - "traefik.enable=true"

  primus:
    container_name: ${SUBDOMAIN:-app}.primus
    depends_on:
      - mongodb
    build: primus
    restart: "always"
    networks:
      - web
      - default
    env_file: env/primus.env
    command: npm start
    ports:
      - "2333:2333"
    labels:
      - "traefik.docker.network=web"
      - "traefik.backend=primus"
      - "traefik.frontend.rule=Host:primus.${SUBDOMAIN:-app}.${DOMAIN:-localhost}"
      - "traefik.port=2333"
      - "traefik.protocol=http"
      - "traefik.enable=true"

  frontend:
    container_name: ${SUBDOMAIN:-app}.frontend
    depends_on:
      - mongodb
    build: frontend
    restart: "always"
    networks:
      - web
      - default
    env_file: env/frontend.env
    ports:
      - "4200:4200"
    labels:
      - "traefik.docker.network=web"
      - "traefik.backend=nginx"
      - "traefik.frontend.rule=Host:${SUBDOMAIN:-app}.${DOMAIN:-localhost}"
      - "traefik.port=80"
      - "traefik.protocol=http"
      - "traefik.enable=true"

networks:
  web:
    external: true