version: '3'
services:
  #  nginx-proxy:
  #    image: jwilder/nginx-proxy
  #    ports:
  #    - "80:80"
  #    volumes:
  #    - /var/run/docker.sock:/tmp/docker.sock:ro

  mongodb:
    build: mongodb
    ports:
    - 27017:27017
    env_file: env/mongodb.env

  backend:
    depends_on:
    - mongodb
    build: backend
    restart: always
    ports:
    - 3000:3000
    env_file: env/backend.env
    command: npm start

  primus:
    depends_on:
    - mongodb
    build: primus
    restart: always
    ports:
    - 2333:2333
    env_file: env/primus.env
    command: npm start

  frontend:
    depends_on:
    - mongodb
    build: frontend
    ports:
    - 4200:80
    env_file: env/frontend.env
