version: '3'
services:
  mongodb:
    build: mongodb
    restart: "always"
    ports:
    - "27017:27017"
    env_file: env/mongodb.env

  backend:
    depends_on:
    - mongodb
    build: backend
    restart: "always"
    ports:
    - "3000:3000"
    expose:
    - "3000"
    env_file: env/backend.env
    command: npm start

  primus:
    depends_on:
    - mongodb
    build: primus
    restart: "always"
    ports:
    - "2333:2333"
    expose:
    - "2333"
    env_file: env/primus.env
    command: npm start

  frontend:
    depends_on:
    - mongodb
    build: frontend
    restart: "always"
    ports:
    - "4200:80"
    expose:
    - "80"
    - "443"
    env_file: env/frontend.env

#networks:
#  default:
#    external:
#      name: nginx-proxy