version: '3'
services:
#  nginx-proxy:
#    image: jwilder/nginx-proxy
#    ports:
#    - "80:80"
#    volumes:
#    - /var/run/docker.sock:/tmp/docker.sock:ro

  mongodb:
    build: mongodb
    ports:
    - 27017:27017
    environment:
    - MONGO_INITDB_ROOT_USERNAME=root
    - MONGO_INITDB_ROOT_PASSWORD=pwd
    - MONGO_INITDB_DATABASE=testdb

  backend:
    depends_on:
    - mongodb
    build: backend
    restart: always
    ports:
    - 3000:3000
    environment:
    - SECRET=lol
    - SERVER_ACCESS_TOKEN=ghjmnbv44cdftgy
    - PRIMUS_URL=http://primus:2333
    env_file: dev.env
    command: npm start

  primus:
    depends_on:
    - mongodb
    build: primus
    restart: always
    ports:
    - 2333:2333
    environment:
    - PORT=2333
    - SERVER_ACCESS_TOKENS="ghjmnbv44cdftgy rtyuh9784b"
    env_file: dev.env
    command: npm start

  frontend:
    depends_on:
    - mongodb
    build: frontend
    ports:
    - 4200:80
    environment:
    - PRIMUS_URL=http://localhost:2333
    env_file: dev.env
