version: '3'
services:
  mongo:
    build: mongodb
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pwd
      MONGO_INITDB_DATABASE: testdb

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
    - 15672:15672
    - 5672:5672