debug = false

logLevel = "ERROR"
# defaultEntryPoints = ["https","http"]
defaultEntryPoints = ["http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
  #   [entryPoints.http.redirect]
  #   entryPoint = "https"
  # [entryPoints.https]
  # address = ":443"
  # [entryPoints.https.tls]

  # [entryPoints.dashboard]
  #   address=":8080"
  #   [entryPoints.dashboard.auth]
  #     [entryPoints.dashboard.auth.basic]
  #       usersFile = "/etc/traefik/.htpasswd"

[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "${HOSTNAME:-localhost}"
watch = true
exposedByDefault = false

# [acme]
# email = "${EMAIL}"
# storage = "acme.json"
# entryPoint = "https"
# onHostRule = true
# [acme.httpChallenge]
# entryPoint = "http"

